import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import Script from 'next/script'
import axios from 'axios';

import Banner from '../components/banner'
import Card from '../components/card'

import { fetchCoffeeStores } from '../lib/coffee-stores-fetch';

export async function getStaticProps() {
  const coffeeStoresFetch = await fetchCoffeeStores(27.07028, -109.44372, process.env.API_KEY_MAPS);

  const data = coffeeStoresFetch;

  return {
    props: { coffeeStores: data },
  }
}

export default function Home(props) {
  const handleOnBannerBtnClick = () => {
    //button handler
  }

  console.log(props.coffeeStores);

  return (
    <div className={styles.container}>
      <Head>
        <title>Café Cercano</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <Script async src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBiYoafozwhiEc8-o5RrHEi4iGH3fJBIyw&libraries=places&callback=initMap"></Script>
      </Head>

      <main className={styles.main}>
        <Banner buttonText="Encuentra cafés cercanos a ti" handleOnClick={handleOnBannerBtnClick} />
        <div className={styles.hero_image} >
          <Image src="/static/hero-image.png" width={700} height={400} />
        </div>
        {props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Cafeterias en Navojoa</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map(store => {
                return (
                  <Card id={store.place_id} name={store.name} imgUrl="https://via.placeholder.com/300.png/09f/fff" href={`/coffee-store/${store.place_id}`} className={styles.card} />
                )
              })}
            </div>
          </>)}
      </main>
    </div>
  )
}
