import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from 'next/image'


import Banner from '../components/banner'
import Card from '../components/card'

import coffeeStoresData from '../data/coffee-stores.json';

export async function getStaticProps() {
  return {
    props: { coffeeStores: coffeeStoresData },
  }
}

export default function Home(props) {
  const handleOnBannerBtnClick = () => {
    //button handler
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Café Cercano</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText="Encuentra cafés cercanos a ti" handleOnClick={handleOnBannerBtnClick} />
        <div className={styles.hero_image} >
          <Image src="/static/hero-image.png" width={700} height={400} />
        </div>
        {props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Cafeterias en Navojoa</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map(store => {
                return (
                  <Card id={store.id} name={store.name} imgUrl={store.imgUrl} href={`/coffee-store/${store.id}`} className={styles.card} />
                )
              })}
            </div>
          </>)}
      </main>
    </div>
  )
}
